---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: nginx-configuration
#   namespace: ingress-nginx
#   labels:
#     app: ingress-nginx
  - name: Deploy Nginx Ingress ConfigMap
    k8s_v1_config_map:
      name: nginx-configuration
      namespace: '{{nginx_ingress_ns}}'
      labels:
        app: ingress-nginx
      data:
        proxy-set-headers: "{{nginx_ingress_ns}}/custom-headers"    
